---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы. 
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Ввод данных покупателя для оформления заказа
  - В каталоге отображается общее количество страниц с товарами
  - При выборе категории товара должна осуществляться фильтрация доступных производителей/брендов
  - Оповещение, что товар добавлен в корзину
  - Отображение картинки товара в корзине
  - При фильтрации по цене результат должен включать введённые значения
  - В фильтре по цене нельзя использовать отрицательные значения
  - Фильтр Категория можно сбросить до состояния "Все товары"
